@startuml
class SecurityContext {
    + SecurityContext(user:Principal?)
    + SecurityContext()
    + authorizeUser(user:Principal?) : void
    + IsUserInRole(role:Role) : bool
    + IsUserInRole(roles:RoleCollection) : bool
}
class "List`1"<T> {
}
SecurityContext --> "LoggedInUser" Principal
@enduml
