@startuml
class SecurityContext {
    + SecurityContext(user:Principal)
    + SecurityContext()
    + isUserInRole(role:Role) : bool
}
class Principal {
    + Principal(name:string, roles:List<Role>)
    + Name : string <<get>>
}
class "List`1"<T> {
}
SecurityContext --> "LoggedInUser" Principal
SecurityContext +-- Principal
Principal --> "roles<Role>" "List`1"
@enduml
