@startuml
class AuthenticationByUsernamePassword {
    + AuthenticationByUsernamePassword(context:SecurityContext, authenticator:IAuthenticator, roleProvider:IRoleProvider)
    + Login(username:string, password:string) : bool
}
class "List`1"<T> {
}
@enduml
